version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/text_to_sql
    env_file:
      - .env
